# messages definition

[up.OdomReport]
x  = "f32"
y  = "f32"
theta = "f32"


[up.SpeedReport]
vx = "f32"
vy = "f32"
vtheta = "f32"

[up.MotorsSpeedReport]
v1 = "f32"
v2 = "f32"
v3 = "f32"

[down.Reset]
flags = "i8"


[down.SpeedCommand]
vx = "f32"
vy = "f32"
vtheta = "f32"

[down.PIDGains]
kp = "f32"
ki = "f32"
kd = "f32"
